// Create web server

// Import express module
const express = require('express');
// Import path module
const path = require('path');
// Import body-parser module
const bodyParser = require('body-parser');
// Import express-handlebars module
const exphbs = require('express-handlebars');
// Import express-messages module
const flash = require('connect-flash');
// Import express-session module
const session = require('express-session');
// Import method-override module
const methodOverride = require('method-override');
// Import mongoose module
const mongoose = require('mongoose');
// Import passport module
const passport = require('passport');